/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Wrapper;

/**
 *
 * @author INSE3D
 */
public class HomePage extends javax.swing.JFrame {

    static final String JDBC_Driver = "com.mysql.jdbc.Driver";
    static final String Database_Path = "jdbc:mysql://167.99.88.104:3306/new?verifyServerCertificate=false&useSSL=true";
    static final String DBUsername = "foodwiseAdmin";
    static final String DBPassword = "Inse3d..";
    Wrapper connect = null;

    /**
     * Creates new form HomePage
     * @param userid
     */
    public HomePage(int userid) {
        this.userid = userid;
        initComponents();
        setResizable(false);
        showAllProducts();
    }
    private int userid = -1;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        showProductDetails = new javax.swing.JTextArea();
        itemsAdded = new javax.swing.JLabel();
        editAProduct = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        deleteAProduct = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Home");

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Log Out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        showProductDetails.setColumns(20);
        showProductDetails.setRows(5);
        jScrollPane2.setViewportView(showProductDetails);

        itemsAdded.setText("You have no added items, click the [+] to add new items to your list!");
        itemsAdded.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                itemsAddedPropertyChange(evt);
            }
        });

        editAProduct.setText("Edit a product");
        editAProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAProductActionPerformed(evt);
            }
        });

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        deleteAProduct.setText("Delete A Product");
        deleteAProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(itemsAdded)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteAProduct)))
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(editAProduct)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemsAdded)
                    .addComponent(jButton1))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(editAProduct)
                    .addComponent(jButton3)
                    .addComponent(deleteAProduct))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Creates a JDialog so the user will be unable to click on the HomePage while on this prompt 
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AddProductInfo dialog = new AddProductInfo(new javax.swing.JFrame(), true, userid);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Label changing text based on if the user has inputted items or not
     * @param evt 
     */
    private void itemsAddedPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_itemsAddedPropertyChange
        if (!itemsAdded.equals("")) {
            itemsAdded.setText("All of your added items are listed below in the text area, click the [+] to add more");
        } else {
            itemsAdded.setText("You have no added items, click the [+] to add new items to your list!");
        }
    }//GEN-LAST:event_itemsAddedPropertyChange

    /**
     * Closes current frame, creates a new login JFrame
     * @param evt 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        Login newLogin = new Login();
        newLogin.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Creates a new EditProductInfo frame, visible to user. 
     * @param evt 
     */
    private void editAProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAProductActionPerformed
        EditProductInfo changeProduct = new EditProductInfo(userid);
        changeProduct.setVisible(true);
    }//GEN-LAST:event_editAProductActionPerformed

    /**
     * Refreshes HomePage, used for when a user has edited their product info
     * @param evt 
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        new HomePage(userid).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * Creates new DeleteProductInfo frame, visible to the user. 
     * @param evt 
     */
    private void deleteAProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAProductActionPerformed
        DeleteProductInfo removeProduct = new DeleteProductInfo(userid);
        removeProduct.setVisible(true);      
    }//GEN-LAST:event_deleteAProductActionPerformed

    /**
     * Displays all current users added products 
     */
    public void showAllProducts() {
        String ProductInformation = "";
        String selectAllProductInformation = "select product_detail from user_details where user_id = " + userid + " order by id desc";
        try {
            connect = DriverManager.getConnection(Database_Path, DBUsername, DBPassword);
            Statement stmt = ((Connection) connect).createStatement();
            stmt.execute(selectAllProductInformation);
            stmt.execute(selectAllProductInformation);
            ResultSet rs = stmt.getResultSet();
            while (rs.next()) {
                ProductInformation = rs.getString(1);
                showProductDetails.append(ProductInformation + "\n") ;
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteAProduct;
    private javax.swing.JButton editAProduct;
    private javax.swing.JLabel itemsAdded;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTextArea showProductDetails;
    // End of variables declaration//GEN-END:variables
}
